version: '3.9'

services:
  app:
    container_name: frontend
    build:
      context: ../
      target: production-stage
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ../:/app
